export interface ClockStyleDefinition {
  id: string;
  nameEn: string;
  nameFa: string;
  category: 'cyber' | 'minimal' | 'retro' | 'chrono' | 'scifi' | 'glow';
  fontFamily?: string;
  clockClass: string;
  secondsClass?: string;
  wrapClass?: string;
  dateClass?: string;
  badge?: string;
}

export const CLOCK_STYLES: ClockStyleDefinition[] = [
  {
    id: 'cyber-neon',
    nameEn: 'Cyberpunk Neon',
    nameFa: 'نئون سایبرپانک',
    category: 'cyber',
    clockClass: 'font-mono text-emerald-300 drop-shadow-[0_0_25px_rgba(52,211,153,0.8)] tracking-tight',
    badge: 'CYBER//01',
  },
  {
    id: 'hacker-terminal',
    nameEn: 'Hacker CRT Terminal',
    nameFa: 'ترمینال هکری CRT',
    category: 'cyber',
    clockClass: 'font-mono text-green-400 drop-shadow-[0_0_15px_#22c55e] tracking-widest',
    badge: 'ROOT@SYS:~#',
  },
  {
    id: 'sci-fi-hud',
    nameEn: 'Sci-Fi Telemetry HUD',
    nameFa: 'تله‌متری علمی‌تخیلی',
    category: 'scifi',
    clockClass: 'font-mono text-cyan-300 drop-shadow-[0_0_20px_#06b6d4] tracking-tighter uppercase',
    badge: 'ORBIT//HUD.7F',
  },
  {
    id: 'retro-flip',
    nameEn: 'Vintage Flip Clock',
    nameFa: 'ساعت ورق‌زن رترو',
    category: 'retro',
    clockClass: 'font-sans font-black text-amber-100 bg-black/60 px-4 py-1 rounded-2xl border border-white/20 shadow-2xl tracking-normal',
    badge: 'RETRO//FLIP',
  },
  {
    id: 'swiss-minimal',
    nameEn: 'Swiss Architecture',
    nameFa: 'معماری سوئیسی مینیمال',
    category: 'minimal',
    clockClass: 'font-sans font-light tracking-[-0.08em] text-white/95',
    badge: 'HELVETICA',
  },
  {
    id: 'tokyo-midnight',
    nameEn: 'Tokyo Midnight Neon',
    nameFa: 'نئون توکیو نیمه‌شب',
    category: 'glow',
    clockClass: 'font-mono font-bold text-fuchsia-400 drop-shadow-[0_0_30px_#e879f9] tracking-normal',
    badge: '東京//MIDNIGHT',
  },
  {
    id: 'nixie-tube',
    nameEn: 'Nixie Tube Vacuum',
    nameFa: 'لامپ نیکسی گرم',
    category: 'retro',
    clockClass: 'font-mono text-amber-500 drop-shadow-[0_0_28px_rgba(245,158,11,0.95)] tracking-widest',
    badge: 'VINTAGE//NIXIE',
  },
  {
    id: 'synthwave-80s',
    nameEn: '80s Synthwave Horizon',
    nameFa: 'سینت‌ویو دهه هشتاد',
    category: 'glow',
    clockClass: 'font-sans font-extrabold bg-gradient-to-r from-pink-500 via-purple-400 to-cyan-400 bg-clip-text text-transparent drop-shadow-[0_0_25px_rgba(236,72,153,0.7)]',
    badge: 'SYNTH//84',
  },
  {
    id: 'led-7segment',
    nameEn: 'Digital 7-Segment LED',
    nameFa: 'دیجیتال ۷-سگمنت',
    category: 'retro',
    clockClass: 'font-mono font-bold text-red-500 drop-shadow-[0_0_18px_#ef4444] tracking-widest',
    badge: 'QUARTZ//DIGITAL',
  },
  {
    id: 'radar-chrono',
    nameEn: 'Military Radar Chrono',
    nameFa: 'رادار کرونوگراف نظامی',
    category: 'chrono',
    clockClass: 'font-mono text-emerald-400 border-b-2 border-emerald-500/40 pb-1 tracking-wider',
    badge: 'RADAR//ACTIVE',
  },
  {
    id: 'binary-matrix',
    nameEn: 'Binary Code Matrix',
    nameFa: 'کد باینری ماتریکس',
    category: 'cyber',
    clockClass: 'font-mono text-emerald-300 drop-shadow-[0_0_20px_#10b981] tracking-wide',
    badge: 'BIN//010110',
  },
  {
    id: 'glitch-cyber',
    nameEn: 'Cybernetic Glitch',
    nameFa: 'گلیچ سایبرنتیک',
    category: 'cyber',
    clockClass: 'font-mono font-black text-white drop-shadow-[2px_2px_0px_#ec4899] drop-shadow-[-2px_-2px_0px_#06b6d4]',
    badge: 'SYS//GLITCH',
  },
  {
    id: 'quantum-orbit',
    nameEn: 'Quantum Orbital Ring',
    nameFa: 'حلقه اوربیتال کوانتومی',
    category: 'scifi',
    clockClass: 'font-sans font-semibold text-sky-200 drop-shadow-[0_0_24px_#38bdf8] tracking-tight',
    badge: 'QUANTUM//CORE',
  },
  {
    id: 'deep-space',
    nameEn: 'Deep Space Nebula',
    nameFa: 'سحابی فضای عمیق',
    category: 'scifi',
    clockClass: 'font-sans font-light text-indigo-200 drop-shadow-[0_0_30px_#818cf8]',
    badge: 'COSMOS//DEEP',
  },
  {
    id: 'military-stencil',
    nameEn: 'Tactical Stencil Spec',
    nameFa: 'استنسیل تاکتیکال',
    category: 'minimal',
    clockClass: 'font-mono font-bold tracking-widest text-zinc-300 uppercase',
    badge: 'SPEC//OPS',
  },
  {
    id: 'pure-oled',
    nameEn: 'Pure Dark OLED Crisp',
    nameFa: 'اولد فوق‌کنتراست خالص',
    category: 'minimal',
    clockClass: 'font-mono font-black text-white tracking-normal',
    badge: 'OLED//PBM',
  },
  {
    id: 'aurora-borealis',
    nameEn: 'Aurora Borealis Glow',
    nameFa: 'شفق قطبی نورانی',
    category: 'glow',
    clockClass: 'font-sans font-bold bg-gradient-to-r from-teal-300 via-emerald-400 to-indigo-400 bg-clip-text text-transparent drop-shadow-[0_0_35px_#2dd4bf]',
    badge: 'AURORA//GLOW',
  },
  {
    id: 'amber-crt',
    nameEn: 'Amber CRT Retro Terminal',
    nameFa: 'ترمینال کهربایی رترو',
    category: 'retro',
    clockClass: 'font-mono text-amber-400 drop-shadow-[0_0_20px_#f59e0b] tracking-wider',
    badge: 'VT220//AMBER',
  },
  {
    id: 'cobalt-vector',
    nameEn: 'Electric Cobalt Blue',
    nameFa: 'آبی کبالت الکتریک',
    category: 'glow',
    clockClass: 'font-mono font-bold text-blue-400 drop-shadow-[0_0_25px_#3b82f6] tracking-tight',
    badge: 'COBALT//VEC',
  },
  {
    id: 'emerald-quartz',
    nameEn: 'Emerald Horology Quartz',
    nameFa: 'کوارتز لوکس زمردی',
    category: 'chrono',
    clockClass: 'font-serif font-light text-emerald-200 drop-shadow-[0_0_15px_rgba(52,211,153,0.5)] tracking-widest',
    badge: 'GENÈVE//QUARTZ',
  },
  {
    id: 'solar-flare',
    nameEn: 'Solar Flare Sunburst',
    nameFa: 'شراره خورشیدی شعله‌ور',
    category: 'glow',
    clockClass: 'font-sans font-black text-orange-400 drop-shadow-[0_0_30px_#fb923c]',
    badge: 'SOLAR//FLARE',
  },
  {
    id: 'arctic-frost',
    nameEn: 'Arctic Cyan Frost',
    nameFa: 'یخین فیروزه‌ای قطبی',
    category: 'glow',
    clockClass: 'font-mono text-cyan-200 drop-shadow-[0_0_22px_#67e8f9] tracking-tighter',
    badge: 'ARCTIC//FROST',
  },
  {
    id: 'violet-phantom',
    nameEn: 'Violet Phantom Stealth',
    nameFa: 'شبح بنفش نئونی',
    category: 'cyber',
    clockClass: 'font-mono font-bold text-purple-400 drop-shadow-[0_0_28px_#a855f7] tracking-wider',
    badge: 'PHANTOM//STEALTH',
  },
  {
    id: 'biohazard-toxic',
    nameEn: 'Toxic Biohazard Neon',
    nameFa: 'سبز بیوهازارد فسفری',
    category: 'cyber',
    clockClass: 'font-mono font-black text-lime-400 drop-shadow-[0_0_28px_#a3e635] tracking-widest',
    badge: 'BIOHAZARD//09',
  },
  {
    id: 'blueprint-draft',
    nameEn: 'Technical Blueprint CAD',
    nameFa: 'نقشه فنی مهندسی CAD',
    category: 'minimal',
    clockClass: 'font-mono text-sky-400 tracking-widest border border-dashed border-sky-400/40 px-3 py-1 rounded-xl',
    badge: 'CAD//SPEC.V4',
  },
  {
    id: 'matrix-rain',
    nameEn: 'Matrix Green Cascade',
    nameFa: 'آبشار سبز ماتریکس',
    category: 'cyber',
    clockClass: 'font-mono font-bold text-emerald-400 drop-shadow-[0_0_20px_#10b981] tracking-widest',
    badge: '01001101',
  },
  {
    id: 'sunset-boulevard',
    nameEn: 'Sunset Boulevard Gradient',
    nameFa: 'غروب آفتاب بولوار',
    category: 'glow',
    clockClass: 'font-sans font-bold bg-gradient-to-r from-amber-400 via-rose-400 to-indigo-400 bg-clip-text text-transparent drop-shadow-[0_0_25px_rgba(251,146,60,0.6)]',
    badge: 'GOLDEN//HOUR',
  },
  {
    id: 'holographic-prism',
    nameEn: 'Holographic Iridescent Prism',
    nameFa: 'منشور رنگین‌کمانی هولوگرام',
    category: 'glow',
    clockClass: 'font-sans font-black bg-gradient-to-r from-cyan-300 via-fuchsia-300 to-amber-200 bg-clip-text text-transparent drop-shadow-[0_0_30px_rgba(232,121,249,0.7)]',
    badge: 'HOLO//PRISM',
  },
  {
    id: 'hyperdrive-warp',
    nameEn: 'Hyperdrive Warp Vector',
    nameFa: 'هایپردرایو بین‌ستاره‌ای',
    category: 'scifi',
    clockClass: 'font-mono italic font-black text-cyan-300 drop-shadow-[0_0_25px_#22d3ee] tracking-tighter',
    badge: 'WARP//SPEED',
  },
  {
    id: 'golden-ratio',
    nameEn: 'Golden Ratio Geometric',
    nameFa: 'نسبت طلایی هندسی',
    category: 'minimal',
    clockClass: 'font-serif text-amber-200 drop-shadow-[0_0_14px_rgba(252,211,77,0.4)] tracking-wider',
    badge: 'PHI//1.618',
  },
  {
    id: 'tachometer-race',
    nameEn: 'RPM Gauge Tachometer',
    nameFa: 'گیج سرعت‌سنج تاکومتر',
    category: 'chrono',
    clockClass: 'font-mono font-black text-red-400 border-l-4 border-red-500 pl-3 tracking-tight',
    badge: 'REDLINE//RPM',
  },
  {
    id: 'glass-frost',
    nameEn: 'Frosted Glass Minimalist',
    nameFa: 'شیشه مات مینیمال',
    category: 'minimal',
    clockClass: 'font-sans font-semibold text-white/90 backdrop-blur-md px-3 py-1 rounded-2xl bg-white/5 border border-white/10',
    badge: 'FROST//GLASS',
  },
  {
    id: 'steampunk-brass',
    nameEn: 'Steampunk Brass Chrono',
    nameFa: 'استیم‌پانک برنجی',
    category: 'retro',
    clockClass: 'font-serif font-bold text-amber-600 drop-shadow-[0_0_18px_rgba(217,119,6,0.6)] tracking-widest',
    badge: 'BRASS//CHRONO',
  },
  {
    id: 'arcade-pixel',
    nameEn: '8-Bit Retro Arcade',
    nameFa: '۸ بیتی بازی‌های آرکید',
    category: 'retro',
    clockClass: 'font-mono font-black text-yellow-300 drop-shadow-[0_0_15px_#fde047] tracking-widest',
    badge: 'INSERT//COIN',
  },
  {
    id: 'carbon-track',
    nameEn: 'Carbon Fiber Sport',
    nameFa: 'فیبر کربن اسپرت',
    category: 'chrono',
    clockClass: 'font-mono font-bold text-zinc-100 bg-zinc-900/80 px-3 py-1 rounded-xl border border-zinc-700 tracking-tight',
    badge: 'CARBON//SPORT',
  },
  {
    id: 'laser-grid',
    nameEn: 'Laser Grid Synth',
    nameFa: 'گرید لیزری سینت',
    category: 'cyber',
    clockClass: 'font-mono font-black text-pink-400 drop-shadow-[0_0_24px_#f472b6] tracking-wider',
    badge: 'LASER//GRID',
  },
  {
    id: 'tachyon-pulse',
    nameEn: 'Tachyon Energy Pulse',
    nameFa: 'تپش انرژی تاکیون',
    category: 'scifi',
    clockClass: 'font-sans font-extrabold text-teal-300 drop-shadow-[0_0_25px_#5eead4] animate-pulse',
    badge: 'TACHYON//PULSE',
  },
  {
    id: 'monolith-slate',
    nameEn: 'Monolith Slate Brutalist',
    nameFa: 'مونولیت اسلیت بروتالیست',
    category: 'minimal',
    clockClass: 'font-mono font-light text-slate-300 tracking-[0.2em] uppercase',
    badge: 'MONOLITH//BRUT',
  },
  {
    id: 'circuit-board',
    nameEn: 'Cyber Circuit Trace',
    nameFa: 'مسیر مدار الکترونیکی',
    category: 'cyber',
    clockClass: 'font-mono text-emerald-400 drop-shadow-[0_0_16px_#34d399] tracking-widest border-b border-emerald-500/30',
    badge: 'PCB//TRACE',
  },
  {
    id: 'executive-chronograph',
    nameEn: 'Executive Chronograph Haute',
    nameFa: 'کرونوگراف کلاسیک اشرافی',
    category: 'chrono',
    clockClass: 'font-serif tracking-widest text-amber-100/90 font-medium',
    badge: 'OFFICIEL//CHRONO',
  },
];
